### ISSUE TITLE
xrange not defined

### ISSUE THREAD

**Issue by ersrin76** [Glank/Galois#1]
on executing your program it says xrange not defined, galois.py line 509.

**Comment by Glank** [comment]
what version of python are you using?

**Comment by ersrin76** [comment]
Sorry, I was using python 3.6.

**Comment by Glank** [comment]
Yeah, this was written for python 2.

**Comment by Glank** [comment]
I'll add a comment in the README

**Comment by ersrin76** [comment]
okk
